name: Build tools cache
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: null

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - ubuntu-18.04
          - macos-10.15
          - ubuntu-20.04
        crate:
          - sccache
          - wasm-bindgen-cli
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build ${{ matrix.crate }}
        run: python build.py
        env:
          CRATE: ${{ matrix.crate }}
          RUNNER: ${{ matrix.os }}
          AWS_S3_REGION: us-west-2
          AWS_S3_BUCKET: rust-tool-cache
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # SIGN_CERT: ${{ secrets.SIGN_CERT }}
          # SIGN_CERT_PASSPHRASE: ${{ secrets.SIGN_CERT_PASSPHRASE }}
